# Workflow para notificar al monorepo cuando hay cambios en main
name: Notify Monorepo on Main Update

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # Permite ejecución manual

jobs:
  notify-monorepo:
    name: Notify Monorepo to Update Submodules
    runs-on: ubuntu-latest
    
    steps:
    - name: Notify monorepo repository
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.MONOREPO_DISPATCH_TOKEN }}
        repository: isidromerayo/TFG_UNIR-monorepo
        event-type: submodule-update
        client-payload: |
          {
            "repository": "TFG_UNIR-backend",
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}",
            "commit_message": "${{ github.event.head_commit.message }}",
            "pusher": "${{ github.event.pusher.name }}",
            "timestamp": "${{ github.event.head_commit.timestamp }}"
          }